### PR TITLE
Update classesGetter.php

### PR DESCRIPTION
**Pull request by lablnet**
Get all classes if you add more file no need to include file its automatically i think its good programmer to write less code do more thanks

### CODE REVIEW

**Comment by yTakkar** [comment]
If you include/require all the class files in `classesGetter.php`, then it will crash. Because some files don't need to be required. I too had an idea to include all files, follow DRY rule but it didn't worked!!

**Review by yTakkar — COMMENTED** [review]
Including all class files in `classesGetter.php` will make page load slower. And some features won't work!!

**Comment by yTakkar** [comment]
Nice to see you contributing in the project. This PR cannot be merged.
Looking forward to upcoming contributions!!
:)

**Comment by lablnet** [comment]
I start working creating admin panel and soon send you poll request

**Pull request closed without merging**
